#!/bin/bash

## Updating Android SDK tools
for i in $(seq 1 5)
do
  list=$(android list sdk --no-ui | grep -e 'SDK Tools' -e 'SDK Platform' -e 'Google API' | awk '{print $1}')
  [ -z "$list" ] && break

  list=$(echo $list | perl -pe 's/-/,/g' | perl -pe 's/ //g' | perl -pe 's/,$//g')
  echo "Updating SDK [$list] ..."
  (while sleep 3; do echo y; done) | android update sdk --no-ui --filter $list
done


## To prevent a gradle error
## https://stackoverflow.com/questions/30952056/ionic-run-android-failed-error-gradle-line-64
if [ -e $ANDROID_HOME/build-tools/android-4.4W ] && [ ! -e $ANDROID_HOME/build-tools/20 ]; then
    echo "Making [$ANDROID_HOME/build-tools/20] ..."
    rsync -avlogp $ANDROID_HOME/build-tools/android-4.4W $ANDROID_HOME/build-tools/20
fi
